
FIND_PATH(GLX_INCLUDE_DIR GL/glx.h
/usr/include
)

FIND_LIBRARY(GLX_LIBRARIES
NAMES GL
PATHS /usr/lib /usr/local/lib
)

SET( GLX_FOUND "NO" )
IF(GLX_LIBRARIES)
    SET( GLX_FOUND "YES" )
    message(STATUS "Found GLX libs: ${GLX_LIBRARIES}")
    message(STATUS "Found GLX includes: ${GLX_INCLUDE_DIR}")
ENDIF(GLX_LIBRARIES)

MARK_AS_ADVANCED(
  GLX_INCLUDE_DIR
  GLX_LIBRARIES
)
